const config = window.PINKCHAT_CONFIG || {};
const $ = (s) => document.querySelector(s);
const demoChats = [{id:'alina',name:'Алина',initials:'А',avatarClass:'avatar-alina',online:true,status:'в сети',unread:2,messages:[{id:'a1',mine:false,body:'Приветик! Ты сегодня свободна? 💕',time:'19:42'},{id:'a2',mine:true,body:'Даа, после восьми точно ✨',time:'19:43',read:true}]}];
const demoStories=[{id:'st1',user:'Алина',initials:'А',avatarClass:'avatar-alina',image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',caption:'Сегодня идеальный день 💗',mine:false,createdAt:Date.now()},{id:'st2',user:'София',initials:'С',avatarClass:'avatar-sofia',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',caption:'Pink mood ✨',mine:false,createdAt:Date.now()}];
const state={mode:'demo',chats:load('pinkchat-demo-chats',demoChats),stories:load('pinkchat-demo-stories',demoStories),activeChatId:'alina',selectedPhoto:null,supabase:null,user:null,profile:load('pinkchat-profile',{displayName:'Томша Евгений',bio:'Создатель PinkChat',theme:'pink',isAdmin:true}),realtimeChannel:null};
const els={app:$('#app'),chatList:$('#chatList'),stories:$('#stories'),totalUnread:$('#totalUnread'),activeAvatar:$('#activeAvatar'),activeName:$('#activeName'),activeStatus:$('#activeStatus'),messages:$('#messages'),form:$('#messageForm'),input:$('#messageInput'),photoInput:$('#photoInput'),photoPreview:$('#photoPreview'),photoPreviewImage:$('#photoPreviewImage'),photoPreviewSize:$('#photoPreviewSize'),emojiPicker:$('#emojiPicker'),modal:$('#modal'),modalContent:$('#modalContent'),toast:$('#toast'),storyViewer:$('#storyViewer'),storyViewerContent:$('#storyViewerContent')};
function load(k,d){try{const v=JSON.parse(localStorage.getItem(k));return v??structuredClone(d)}catch{return structuredClone(d)}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function id(){return crypto.randomUUID?.()||`pc-${Date.now()}`}
function time(){return new Intl.DateTimeFormat('ru',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function active(){return state.chats.find(c=>c.id===state.activeChatId)}
function applyTheme(){document.documentElement.dataset.theme=state.profile.theme||'pink';save('pinkchat-profile',state.profile)}
function renderStories(){els.stories.innerHTML='';const add=document.createElement('button');add.className='story add-story';add.innerHTML='<span class="story-avatar">＋</span><span>Твоя история</span>';add.onclick=showAddStory;els.stories.append(add);state.stories.slice(0,10).forEach(st=>{const b=document.createElement('button');b.className='story';b.innerHTML=`<span class="story-ring"><span class="story-avatar ${st.avatarClass}">${esc(st.initials)}</span></span><span>${esc(st.user)}</span>`;b.onclick=()=>openStory(st);els.stories.append(b)})}
function renderChatList(filter=''){renderStories();els.chatList.innerHTML='';const q=filter.trim().toLowerCase();state.chats.filter(c=>!q||c.name.toLowerCase().includes(q)||(c.messages.at(-1)?.body||'').toLowerCase().includes(q)).forEach(c=>{const last=c.messages.at(-1);const b=document.createElement('button');b.className=`chat-item ${c.id===state.activeChatId?'active':''}`;b.innerHTML=`<span class="chat-avatar ${c.avatarClass} ${c.online?'online':''}">${esc(c.initials)}</span><span class="chat-main"><span class="chat-name-row"><strong>${esc(c.name)}</strong><time>${esc(last?.time||'')}</time></span><span class="chat-preview-row"><span class="chat-preview">${last?.image?'📷 Фото':esc(last?.body||'Начните общение')}</span>${c.unread?`<span class="unread">${c.unread}</span>`:''}</span></span>`;b.onclick=()=>openChat(c.id);els.chatList.append(b)});const u=state.chats.reduce((s,c)=>s+(c.unread||0),0);els.totalUnread.textContent=u?`${u} новых`:'всё прочитано'}
function renderActive(){const c=active();if(!c){els.messages.innerHTML='<div class="day-divider">Создай чат 💗</div>';return}els.activeAvatar.className=`active-avatar ${c.avatarClass}`;els.activeAvatar.textContent=c.initials;els.activeName.textContent=c.name;els.activeStatus.innerHTML=c.online?'<span class="online-dot"></span> в сети':'была недавно';els.messages.innerHTML='<div class="day-divider">Сегодня</div>';c.messages.forEach(m=>els.messages.append(messageNode(m,c)));requestAnimationFrame(()=>els.messages.scrollTop=els.messages.scrollHeight)}
function messageNode(m,c){const row=document.createElement('div');row.className=`message-row ${m.mine?'mine':'theirs'}`;const bubble=document.createElement('div');bubble.className='bubble';if(m.image){const img=document.createElement('img');img.src=m.image;img.className='message-photo';img.onclick=()=>openImage(m.image);bubble.append(img)}if(m.body){const p=document.createElement('p');p.textContent=m.body;bubble.append(p)}const meta=document.createElement('div');meta.className='message-meta';meta.innerHTML=`<span>${esc(m.edited?'изм. ': '')}${esc(m.time||'')}</span>${m.mine?'<span>✓✓</span>':''}`;bubble.append(meta);if(m.mine){bubble.addEventListener('contextmenu',e=>{e.preventDefault();showMessageMenu(m)});bubble.addEventListener('dblclick',()=>showMessageMenu(m));row.append(bubble)}else{const av=document.createElement('span');av.className=`message-mini-avatar ${c.avatarClass}`;av.textContent=c.initials;row.append(av,bubble)}return row}
function openChat(cid){state.activeChatId=cid;const c=active();if(c)c.unread=0;save('pinkchat-demo-chats',state.chats);renderChatList($('#chatSearch').value);renderActive();els.app.classList.add('chat-open')}
function clearComposer(){els.input.value='';els.input.style.height='auto';state.selectedPhoto=null;els.photoInput.value='';els.photoPreview.classList.add('hidden')}
function sendMessage(e){e.preventDefault();const body=els.input.value.trim();if(!body&&!state.selectedPhoto)return;const c=active();c.messages.push({id:id(),mine:true,body,image:state.selectedPhoto?.dataUrl||null,time:time(),read:true});clearComposer();save('pinkchat-demo-chats',state.chats);renderChatList();renderActive()}
function showMessageMenu(m){openModal(`<h2>Сообщение</h2><button class="modal-action" id="editMsg">✏️ Редактировать</button><button class="modal-action danger" id="deleteMsg">🗑 Удалить</button>`);$('#editMsg').onclick=()=>{els.modal.close();const v=prompt('Новый текст',m.body||'');if(v!==null){m.body=v.trim();m.edited=true;save('pinkchat-demo-chats',state.chats);renderActive();renderChatList()}};$('#deleteMsg').onclick=()=>{const c=active();c.messages=c.messages.filter(x=>x.id!==m.id);save('pinkchat-demo-chats',state.chats);els.modal.close();renderActive();renderChatList()}}
function showAddStory(){openModal(`<h2>Новая история</h2><p class="modal-lead">Фото исчезнет через 24 часа.</p><input id="storyFile" class="modal-input" type="file" accept="image/*"><input id="storyCaption" class="modal-input" placeholder="Подпись"><button id="publishStory" class="primary-button" type="button">Опубликовать</button>`);$('#publishStory').onclick=()=>{const f=$('#storyFile').files[0];if(!f)return toast('Выбери фото');const r=new FileReader();r.onload=()=>{state.stories.unshift({id:id(),user:state.profile.displayName||'Ты',initials:(state.profile.displayName||'Т')[0],avatarClass:'avatar-liza',image:r.result,caption:$('#storyCaption').value,mine:true,createdAt:Date.now()});save('pinkchat-demo-stories',state.stories);els.modal.close();renderStories();toast('История опубликована 💗')};r.readAsDataURL(f)}}
function openStory(st){els.storyViewerContent.innerHTML=`<div class="story-media"><img src="${st.image}" alt="История"><div class="story-caption"><strong>${esc(st.user)}</strong><p>${esc(st.caption||'')}</p></div></div>`;els.storyViewer.showModal()}
function showProfile(){openModal(`<h2>${state.profile.isAdmin?'👑 Админ-профиль':'Профиль'}</h2><label class="modal-label">Имя<input id="profileName" class="modal-input" value="${esc(state.profile.displayName||'')}"></label><label class="modal-label">О себе<textarea id="profileBio" class="modal-input">${esc(state.profile.bio||'')}</textarea></label><label class="modal-label">Тема<select id="profileTheme" class="modal-input"><option value="pink">Розовая</option><option value="purple">Фиолетовая</option><option value="dark">Тёмная</option><option value="peach">Персиковая</option></select></label><button id="saveProfile" class="primary-button" type="button">Сохранить</button>${state.profile.isAdmin?'<button id="adminPanel" class="modal-action">⚡ Админ-панель</button>':''}`);$('#profileTheme').value=state.profile.theme||'pink';$('#saveProfile').onclick=()=>{state.profile.displayName=$('#profileName').value.trim()||'Пользователь';state.profile.bio=$('#profileBio').value.trim();state.profile.theme=$('#profileTheme').value;applyTheme();els.modal.close();toast('Профиль сохранён')};if($('#adminPanel'))$('#adminPanel').onclick=showAdmin}
function showAdmin(){openModal(`<h2>⚡ Админ-панель</h2><div class="admin-grid"><div><strong>${state.chats.length}</strong><span>чатов</span></div><div><strong>${state.stories.length}</strong><span>историй</span></div><div><strong>${state.chats.reduce((s,c)=>s+c.messages.length,0)}</strong><span>сообщений</span></div></div><button id="broadcastBtn" class="primary-button" type="button">Разослать объявление</button><button id="clearStoriesBtn" class="modal-action danger" type="button">Удалить все истории</button>`);$('#broadcastBtn').onclick=()=>{const t=prompt('Текст объявления');if(t){state.chats.forEach(c=>c.messages.push({id:id(),mine:false,body:`📢 ${t}`,time:time()}));save('pinkchat-demo-chats',state.chats);toast('Объявление добавлено');els.modal.close();renderChatList();renderActive()}};$('#clearStoriesBtn').onclick=()=>{state.stories=[];save('pinkchat-demo-stories',state.stories);els.modal.close();renderStories();toast('Истории очищены')}}
function openImage(src){openModal(`<img class="modal-image" src="${src}" alt="Фото">`)}
function openModal(html){els.modalContent.innerHTML=html;els.modal.showModal()}
function toast(t){els.toast.textContent=t;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
function handlePhoto(file){if(!file)return;const r=new FileReader();r.onload=()=>{state.selectedPhoto={dataUrl:r.result};els.photoPreviewImage.src=r.result;els.photoPreviewSize.textContent=`${Math.round(file.size/1024)} КБ`;els.photoPreview.classList.remove('hidden')};r.readAsDataURL(file)}
function init(){applyTheme();renderChatList();renderActive();els.form.onsubmit=sendMessage;$('#chatSearch').oninput=e=>renderChatList(e.target.value);$('#backButton').onclick=()=>els.app.classList.remove('chat-open');$('#attachButton').onclick=()=>els.photoInput.click();els.photoInput.onchange=e=>handlePhoto(e.target.files[0]);$('#removePhotoButton').onclick=clearComposer;$('#settingsButton').onclick=showProfile;$('#addStoryButton').onclick=showAddStory;$('#notificationButton').onclick=async()=>{if(!('Notification'in window))return toast('Уведомления не поддерживаются');const p=await Notification.requestPermission();toast(p==='granted'?'Уведомления включены 🔔':'Разрешение не выдано')};const emojis=['💗','💕','✨','😍','🥰','😂','🔥','🎀','💅','🌸','😭','😘'];els.emojiPicker.innerHTML=emojis.map(x=>`<button type="button">${x}</button>`).join('');els.emojiPicker.querySelectorAll('button').forEach(b=>b.onclick=()=>{els.input.value+=b.textContent;els.input.focus()});$('#emojiButton').onclick=()=>els.emojiPicker.classList.toggle('hidden');els.input.oninput=()=>{els.input.style.height='auto';els.input.style.height=`${Math.min(els.input.scrollHeight,120)}px`};$('#chatMenuButton').onclick=()=>openModal('<h2>Чат</h2><button class="modal-action">🔕 Отключить уведомления</button><button class="modal-action danger">🗑 Очистить историю</button>');$('#searchMessagesButton').onclick=()=>{const q=prompt('Найти сообщение');if(q){const found=active()?.messages.find(m=>(m.body||'').toLowerCase().includes(q.toLowerCase()));toast(found?`Найдено: ${found.body}`:'Не найдено')}}}
init();
